{-# LANGUAGE BangPatterns, GADTs, UnboxedTuples, MagicHash, PatternSynonyms, ViewPatterns, TypeFamilies #-}
-- | A strict, finger-tree style deque.
--
-- * worst-case O(1) 'cons', 'snoc', 'uncons', 'unsnoc', 'size'
-- * O(log n) 'lookup', 'append', 'take', 'drop'
-- * O(n) 'fromList', 'toList'
-- * no laziness anywhere: every field is strict, nothing is a thunk
--
module Unison.Util.Deque
  ( -- * The type
    Deque
  , Seq
  , pattern Empty, pattern (:<|), pattern (:|>)
    -- * Construction
  , empty, singleton
  , cons, snoc, append
  , (<|), (|>), (><)
  , fromList, fromFunction
    -- * Queries
  , size, length, null
  , lookup
  , toList
    -- * Taking apart
  , uncons, unsnoc
  , take, drop, splitAt
    -- * Whole-sequence transformations (these rebuild the sequence)
  , sort, sortBy, unstableSort, unstableSortBy
  , intersperse, reverse
    -- * For tests
  , valid
  ) where

import Prelude hiding (take, drop, lookup, length, null, splitAt, reverse)
import Control.DeepSeq (NFData (..))
import Control.Monad (unless, when, zipWithM_)
import Data.Functor.Classes (Eq1 (..), Ord1 (..), Show1 (..))
import GHC.Exts (Int (I#), Int#)
import Data.Bits (unsafeShiftL, unsafeShiftR, (.&.))
import qualified Data.Foldable as F
import qualified Data.List as L
import qualified GHC.Exts as Exts

------------------------------------------------------------------------
-- Parameters.  A repair moves one Node of 'wNode' elements between a level
-- and the one below.  Digit sizes: green 2..bGreen, yellow 1 and bGreen+1,
-- red 0 and bGreen+2.  Any bGreen >= wNode + 1 works (wNode = 2, bGreen = 3
-- is the classic 0..5 scheme); the minimum keeps repairs cheapest.

wNode :: Int
wNode = 8

bGreen :: Int
bGreen = wNode + 1

------------------------------------------------------------------------
-- Strict lists (digits), and nodes.  Digits are short lists; the bulk of the
-- data lives in nodes.  A node's first field is the number of leaves under
-- it.  Nodes made by repairs (shedding a full digit) have eight children;
-- 'append' may also make nodes of three or two.

data SList a = SEmpty | SCons !a !(SList a)

-- If built via `cons` and `snoc`, a `Deque` will only contain
-- `N8` nodes. `N2` and `N3` are needed for symmetry breaking in `append`,
-- and can sometimes be generated by `take` and `drop`.
data Node a
  = N8 !Int !a !a !a !a !a !a !a !a
  | N3 !Int !a !a !a
  | N2 !Int !a !a

nodeSize :: Node a -> Int
nodeSize (N8 n _ _ _ _ _ _ _ _) = n
nodeSize (N3 n _ _ _)           = n
nodeSize (N2 n _ _)             = n
{-# INLINE nodeSize #-}

nodeArity :: Node a -> Int
nodeArity (N8 {}) = 8
nodeArity (N3 {}) = 3
nodeArity (N2 {}) = 2
{-# INLINE nodeArity #-}

-- first eight cells of a list that runs in sequence order; the node of eight
-- leaves (level 1) or of eight nodes (deeper)
nodeFromFwd :: SList a -> Node a
nodeFromFwd (SCons a (SCons b (SCons c (SCons d (SCons e (SCons f (SCons g (SCons h _))))))))
  = N8 8 a b c d e f g h
nodeFromFwd _ = error "nodeFromFwd: short list"

nodeFromBwd :: SList a -> Node a
nodeFromBwd (SCons h (SCons g (SCons f (SCons e (SCons d (SCons c (SCons b (SCons a _))))))))
  = N8 8 a b c d e f g h
nodeFromBwd _ = error "nodeFromBwd: short list"

nodeFromFwdN :: SList (Node y) -> Node (Node y)
nodeFromFwdN (SCons a (SCons b (SCons c (SCons d (SCons e (SCons f (SCons g (SCons h _))))))))
  = N8 (nodeSize a + nodeSize b + nodeSize c + nodeSize d + nodeSize e + nodeSize f + nodeSize g + nodeSize h)
       a b c d e f g h
nodeFromFwdN _ = error "nodeFromFwdN: short list"

nodeFromBwdN :: SList (Node y) -> Node (Node y)
nodeFromBwdN (SCons h (SCons g (SCons f (SCons e (SCons d (SCons c (SCons b (SCons a _))))))))
  = N8 (nodeSize a + nodeSize b + nodeSize c + nodeSize d + nodeSize e + nodeSize f + nodeSize g + nodeSize h)
       a b c d e f g h
nodeFromBwdN _ = error "nodeFromBwdN: short list"

nodeToFwd, nodeToBwd :: Node a -> SList a
nodeToFwd (N8 _ a b c d e f g h) =
  SCons a (SCons b (SCons c (SCons d (SCons e (SCons f (SCons g (SCons h SEmpty)))))))
nodeToFwd (N3 _ a b c) = SCons a (SCons b (SCons c SEmpty))
nodeToFwd (N2 _ a b)   = SCons a (SCons b SEmpty)
nodeToBwd (N8 _ a b c d e f g h) =
  SCons h (SCons g (SCons f (SCons e (SCons d (SCons c (SCons b (SCons a SEmpty)))))))
nodeToBwd (N3 _ a b c) = SCons c (SCons b (SCons a SEmpty))
nodeToBwd (N2 _ a b)   = SCons b (SCons a SEmpty)

-- the k-th child (0-based)
nodeAt :: Int -> Node a -> a
nodeAt k (N8 _ a b c d e f g h) = case k of
  0 -> a; 1 -> b; 2 -> c; 3 -> d; 4 -> e; 5 -> f; 6 -> g; _ -> h
nodeAt k (N3 _ a b c) = case k of { 0 -> a; 1 -> b; _ -> c }
nodeAt k (N2 _ a b)   = case k of { 0 -> a; _ -> b }

takeS :: Int -> SList a -> SList a
takeS 0 _            = SEmpty
takeS k (SCons x r)  = SCons x (takeS (k - 1) r)
takeS _ SEmpty       = SEmpty

dropS :: Int -> SList a -> SList a
dropS 0 l            = l
dropS k (SCons _ r)  = dropS (k - 1) r
dropS _ SEmpty       = SEmpty

appendS :: SList a -> SList a -> SList a
appendS SEmpty ys       = ys
appendS (SCons x r) ys  = SCons x (appendS r ys)

------------------------------------------------------------------------
-- A digit is a buffer with its element count and the number of leaves under
-- its elements.  The list runs outermost element first: front of a prefix,
-- back of a suffix.  So cons/snoc/uncons/unsnoc are plain list cons/uncons.
-- Only the repair step touches the inner end.
--
-- The leaf count is what lets 'index' skip over a whole digit without
-- touching its nodes.  It is kept up to date for digits below the top level
-- (whose elements are nodes); for the top level, where an element is one
-- leaf, it is not maintained (the count is the leaf count).

data Dig a = Dig !Int !Int !(SList a)

dnil :: Dig a
dnil = Dig 0 0 SEmpty

dcount :: Dig a -> Int
dcount (Dig n _ _) = n
{-# INLINE dcount #-}

dpop :: Dig a -> (a, Dig a)                    -- outer end; needs count >= 1
dpop (Dig n z (SCons x l)) = (x, Dig (n - 1) z l)
dpop (Dig _ _ SEmpty)      = error "dpop: empty digit"
{-# INLINE dpop #-}

-- the same, keeping the leaf count (given the size of one element)
dpushS :: (a -> Int) -> a -> Dig a -> Dig a
dpushS sz x (Dig n z l) = Dig (n + 1) (z + sz x) (SCons x l)
{-# INLINE dpushS #-}

dpopS :: (a -> Int) -> Dig a -> (a, Dig a)
dpopS sz (Dig n z (SCons x l)) = (x, Dig (n - 1) (z - sz x) l)
dpopS _ (Dig _ _ SEmpty)       = error "dpopS: empty digit"
{-# INLINE dpopS #-}

-- Shed the wNode innermost elements as a Node in sequence order.  The prefix
-- list runs in sequence order and the suffix list runs backwards, so each
-- matches straight into the node's fields.
shedP, shedS :: Dig a -> (Dig a, Node a)
shedP (Dig n z l) =
  let !k = n - wNode
      !front = Dig k z (takeS k l)
      !nd = nodeFromFwd (dropS k l)
  in (front, nd)
shedS (Dig n z l) =
  let !k = n - wNode
      !front = Dig k z (takeS k l)
      !nd = nodeFromBwd (dropS k l)
  in (front, nd)

-- The same one level down, where the elements are themselves nodes and the
-- new node's size is the sum of theirs.
shedPN, shedSN :: Dig (Node y) -> (Dig (Node y), Node (Node y))
shedPN (Dig n z l) =
  let !k = n - wNode
      !nd = nodeFromFwdN (dropS k l)
      !front = Dig k (z - nodeSize nd) (takeS k l)
  in (front, nd)
shedSN (Dig n z l) =
  let !k = n - wNode
      !nd = nodeFromBwdN (dropS k l)
      !front = Dig k (z - nodeSize nd) (takeS k l)
  in (front, nd)

-- Take a Node (of any arity) onto the inner end.
pullP, pullS :: Dig a -> Node a -> Dig a
pullP (Dig n z l) nd = Dig (n + nodeArity nd) (z + nodeSize nd) (appendS l (nodeToFwd nd))
pullS (Dig n z l) nd = Dig (n + nodeArity nd) (z + nodeSize nd) (appendS l (nodeToBwd nd))

------------------------------------------------------------------------
-- Levels: a prefix and a suffix.  The level's sequence is prefix ++ suffix
-- (a suffix's slots run back to front).

data Lvl a = Lvl {-# UNPACK #-} !(Dig a) {-# UNPACK #-} !(Dig a)

-- A level from its t elements in sequence order: the first k go to the
-- prefix, the rest to the suffix.
splitLvl :: (a -> Int) -> Int -> Int -> SList a -> Lvl a
splitLvl sz k t xs = Lvl (mkDig sz k (takeS k xs)) (mkDig sz (t - k) (revS (dropS k xs)))

isEmptyLvl :: Lvl a -> Bool
isEmptyLvl (Lvl p s) = dcount p == 0 && dcount s == 0

-- Colors: red < yellow < green.  The bottom level ignores an empty digit.
data Color = Red | Yellow | Green deriving (Eq, Ord, Show)

ccolor :: Int -> Color
ccolor n
  | n >= 2 && n <= bGreen = Green
  | n == 1 || n == bGreen + 1 = Yellow
  | otherwise = Red
{-# INLINE ccolor #-}

lcolorN :: Bool -> Int -> Int -> Color
lcolorN bottom np ns
  | bottom && np == 0 = if ns == 0 then Green else ccolor ns
  | bottom && ns == 0 = ccolor np
  | otherwise         = min (ccolor np) (ccolor ns)
{-# INLINE lcolorN #-}

lcolor :: Bool -> Lvl a -> Color
lcolor bottom (Lvl p s) = lcolorN bottom (dcount p) (dcount s)
{-# INLINE lcolor #-}

-- Push/pop at either end of a level's sequence (sz: size of one element,
-- for the leaf counts).
pushF, pushB :: (a -> Int) -> a -> Maybe (Lvl a) -> Lvl a
pushF sz e Nothing          = Lvl (dpushS sz e dnil) dnil
pushF sz e (Just (Lvl p s)) = Lvl (dpushS sz e p) s
pushB sz e Nothing          = Lvl dnil (dpushS sz e dnil)
pushB sz e (Just (Lvl p s)) = Lvl p (dpushS sz e s)

popF, popB :: (a -> Int) -> Lvl a -> Maybe (a, Lvl a)
popF sz (Lvl p s)
  | dcount p > 0 = case dpopS sz p of (x, p') -> Just (x, Lvl p' s)
  -- A bottom level with an empty prefix: share out what is left between the
  -- two digits, so that the pops that follow find a prefix.  (Up to three
  -- elements all go to the near digit.)
  | otherwise    = case revS (dBwd s) of
      SCons x xs -> let r = dcount s - 1
                    in Just (x, splitLvl sz (if r <= 3 then r else r `div` 2) r xs)
      SEmpty     -> Nothing
popB sz (Lvl p s)
  | dcount s > 0 = case dpopS sz s of (x, s') -> Just (x, Lvl p s')
  | otherwise    = case revS (dFwd p) of       -- the mirror image; xs runs back to front
      SCons x xs -> let r = dcount p - 1
                        k = if r <= 3 then r else r `div` 2
                    in Just (x, Lvl (mkDig sz (r - k) (revS (dropS k xs))) (mkDig sz k (takeS k xs)))
      SEmpty     -> Nothing

------------------------------------------------------------------------
-- General (slow-path) repair: make a level green using at most one
-- node-move per end of the level below.  Pushes happen before pulls so a
-- bottom level can feed itself.  Nothing for the next level means "absent";
-- the result is Nothing if the next level was (or became) an empty bottom.

makeGreen :: (Dig a -> (Dig a, Node a)) -> (Dig a -> (Dig a, Node a)) -> (a -> Int)
          -> Bool -> Lvl a -> Maybe (Lvl (Node a)) -> (Lvl a, Maybe (Lvl (Node a)))
makeGreen shP shS sz nextLast (Lvl p s) ml0 =
  let lastFlag = case ml0 of { Nothing -> True; Just _ -> nextLast }
      (p1, ml1)
        | dcount p > bGreen = case shP p of
            (p', nd) -> (p', Just (pushF nodeSize nd ml0))
        | otherwise = (p, ml0)
      (s1, ml2)
        | dcount s > bGreen = case shS s of
            (s', nd) -> (s', Just (pushB nodeSize nd ml1))
        | otherwise = (s, ml1)
      (p2, ml3)
        | dcount p1 < 2 = case ml2 >>= popF nodeSize of
            Just (nd, l') -> (pullP p1 nd, Just l')
            Nothing            -> (p1, ml2)
        | otherwise = (p1, ml2)
      (s2, ml4)
        | dcount s1 < 2 = case ml3 >>= popB nodeSize of
            Just (nd, l') -> (pullS s1 nd, Just l')
            Nothing            -> (s1, ml3)
        | otherwise = (s1, ml3)
      ml5 = case ml4 of
        Just l | lastFlag, isEmptyLvl l -> Nothing
        _                               -> ml4
      r' = Lvl p2 s2
  in case ml5 of
       Nothing -> (canonBottom sz r', Nothing)
       Just _  -> (r', ml5)

-- A bottom level with no level beneath it: rebalance its two digits.
canonBottom :: (a -> Int) -> Lvl a -> Lvl a
canonBottom sz l@(Lvl p s)
  | t <= 3          = if dcount s == 0 then l else Lvl (mkDig sz t xs) dnil
  | t <= 2 * bGreen = if ccolor (dcount p) == Green && ccolor (dcount s) == Green then l
                      else splitLvl sz (t `div` 2) t xs
  | otherwise       = l
  where t  = dcount p + dcount s
        xs = appendS (dFwd p) (revS (dBwd s))

------------------------------------------------------------------------
-- Levels are grouped K-T style.  The top level's digits live directly in
-- the Deque; below them come the yellow levels of the top run ('tl'), then
-- a stack of substacks, each a non-yellow head level followed by a run of
-- yellows.  A yellow top level belongs to the top run; a green one heads the
-- first substack, with 'tl' as its run.  Every field is strict.
--
-- Ys a b is a run of yellow levels from element type a down to b.  Every
-- level below the top holds Nodes, which the GADT constructors record.

data Ys a b where
  YN :: Ys a a
  YC :: {-# UNPACK #-} !(Lvl (Node a)) -> !(Ys (Node (Node a)) b) -> Ys (Node a) b

data Sub a b = Sub {-# UNPACK #-} !(Lvl a) !(Ys (Node a) b)

data Subs a where
  SN :: Subs a
  SC :: !(Sub (Node x) b) -> !(Subs b) -> Subs (Node x)

data Deque a where
  Nil :: Deque a
  -- total element count, prefix (count, elements), suffix (count, elements),
  -- yellow run below, substacks.  (The top digits are kept as plain fields so
  -- that the fast paths carry no leaf counts.)
  Deque :: {-# UNPACK #-} !Int -> {-# UNPACK #-} !Int -> !(SList a) -> {-# UNPACK #-} !Int -> !(SList a) -> !(Ys (Node a) b) -> !(Subs b) -> Deque a

isYN :: Ys a b -> Bool
isYN YN = True
isYN _  = False

isSN :: Subs a -> Bool
isSN SN = True
isSN _  = False

empty :: Deque a
empty = Nil

mkDeque :: Int -> Dig a -> Dig a -> Ys (Node a) b -> Subs b -> Deque a
mkDeque sz (Dig n _ l) (Dig m _ r) tl subs = Deque sz n l m r tl subs
{-# INLINE mkDeque #-}

lcolorD :: Bool -> Dig a -> Dig a -> Color
lcolorD bottom p s = lcolorN bottom (dcount p) (dcount s)
{-# INLINE lcolorD #-}

-- Put a modified top level back.  sz is the new total size, (np, ns) the old
-- top's digit sizes, (p', s') the new digits.
-- Only a red result, or a green head turning yellow, can expose a red first
-- non-yellow level, so only those cases look further down.
place :: Int -> Int -> Int -> Dig a -> Dig a -> Ys (Node a) b -> Subs b -> Deque a
place !sz !np !ns p' s' tl subs
  | bottom && dcount p' == 0 && dcount s' == 0 = Nil
  | otherwise = case lcolorD bottom p' s' of
      Green  -> mkDeque sz p' s' tl subs
      Yellow | lcolorN bottom np ns == Yellow -> mkDeque sz p' s' tl subs
             | otherwise                      -> mkDeque sz p' s' tl (regularizeSubs subs)
      Red    -> fixTopRed sz p' s' tl subs
  where bottom = isYN tl && isSN subs

-- One end of a repair: a digit above bGreen sheds a node downward, a digit
-- below 2 pulls one up, anything else is left alone.
actP, actS :: (Dig a -> (Dig a, Node a)) -> Dig a -> Dig (Node a) -> (Dig a -> Dig (Node a) -> r) -> r
actP shP p lp k
  | np > bGreen = case shP p of (p', nd) -> k p' (dpushS nodeSize nd lp)
  | np < 2      = case dpopS nodeSize lp of (nd, lp') -> k (pullP p nd) lp'
  | otherwise   = k p lp
  where np = dcount p
actS shS s ls k
  | ns > bGreen = case shS s of (s', nd) -> k s' (dpushS nodeSize nd ls)
  | ns < 2      = case dpopS nodeSize ls of (nd, ls') -> k (pullS s nd) ls'
  | otherwise   = k s ls
  where ns = dcount s
{-# INLINE actP #-}
{-# INLINE actS #-}

-- Repair a red level (p, s) given the level below it.  When that level is
-- not the bottom, both of its digits are non-empty and non-full, so the
-- moves are straight list operations with no intermediate allocation (the
-- same goes for a bottom level with enough in the digits that are needed);
-- everything else goes through the general makeGreen.  kJ gets the new
-- digits and the new level below; kN just the new digits when the level
-- below vanished.
repair :: (Dig a -> (Dig a, Node a)) -> (Dig a -> (Dig a, Node a)) -> (a -> Int)
       -> Dig a -> Dig a -> Maybe (Lvl (Node a)) -> Bool
       -> (Dig a -> Dig a -> Lvl (Node a) -> r) -> (Dig a -> Dig a -> r) -> r
repair shP shS sz p s ml0 nextLast kJ kN = case ml0 of
    Just (Lvl lp ls) | not nextLast || bottomSupplies lp ls ->
      actP shP p lp (\p1 lp1 -> actS shS s ls (\s1 ls1 -> kJ p1 s1 (Lvl lp1 ls1)))
    _ -> slow
  where
    -- a bottom level may have an empty digit, and must not be left empty
    bottomSupplies lp ls =
      let needP = if dcount p < 2 then 1 else 0 :: Int
          needS = if dcount s < 2 then 1 else 0
      in dcount lp >= needP && dcount ls >= needS && dcount lp + dcount ls > needP + needS
    slow = case makeGreen shP shS sz nextLast (Lvl p s) ml0 of
      (Lvl p' s', Nothing)  -> kN p' s'
      (Lvl p' s', Just l1') -> kJ p' s' l1'
{-# INLINE repair #-}

fixTopRed :: Int -> Dig a -> Dig a -> Ys (Node a) b -> Subs b -> Deque a
fixTopRed sz p s tl subs = case tl of
  YC l1 yt -> fixVia sz p s l1 yt subs
  YN -> case subs of
    SC (Sub l1 yt) st -> fixVia sz p s l1 yt st
    -- the only level, and what it holds fits in two green digits: rebalance
    SN | dcount p + dcount s <= 2 * bGreen ->
           case canonBottom (const 0) (Lvl p s) of Lvl p' s' -> mkDeque sz p' s' YN SN
    SN -> repair shedP shedS (const 0) p s Nothing True
            (\p' s' l1' -> case lcolor True l1' of
                 Yellow -> mkDeque sz p' s' (YC l1' YN) SN
                 _      -> mkDeque sz p' s' YN (SC (Sub l1' YN) SN))
            (\p' s' -> mkDeque sz p' s' YN SN)

fixVia :: Int -> Dig a -> Dig a -> Lvl (Node a) -> Ys (Node (Node a)) c -> Subs c -> Deque a
fixVia sz p s l1 yt st =
  let lst = isYN yt && isSN st
  in repair shedP shedS (const 0) p s (Just l1) lst
       (\p' s' l1' -> case lcolor lst l1' of
            Yellow -> mkDeque sz p' s' (YC l1' yt) st
            _      -> mkDeque sz p' s' YN (SC (Sub l1' yt) st))
       (\p' s' -> mkDeque sz p' s' YN SN)

-- Fix the red head of the first substack (r, rest); 'subs' follow it.
fixSub :: Lvl (Node x) -> Ys (Node (Node x)) b -> Subs b -> Subs (Node x)
fixSub (Lvl p s) rest subs = case rest of
  YC l1 yt -> fixSubVia p s l1 yt subs
  YN -> case subs of
    SC (Sub l1 yt) st -> fixSubVia p s l1 yt st
    SN -> repair shedPN shedSN nodeSize p s Nothing True
            (\p' s' l1' -> case lcolor True l1' of
                 Yellow -> SC (Sub (Lvl p' s') (YC l1' YN)) SN
                 _      -> SC (Sub (Lvl p' s') YN) (SC (Sub l1' YN) SN))
            (\p' s' -> SC (Sub (Lvl p' s') YN) SN)

fixSubVia :: Dig (Node x) -> Dig (Node x) -> Lvl (Node (Node x)) -> Ys (Node (Node (Node x))) c -> Subs c -> Subs (Node x)
fixSubVia p s l1 yt st =
  let lst = isYN yt && isSN st
  in repair shedPN shedSN nodeSize p s (Just l1) lst
       (\p' s' l1' -> case lcolor lst l1' of
            Yellow -> SC (Sub (Lvl p' s') (YC l1' yt)) st
            _      -> SC (Sub (Lvl p' s') YN) (SC (Sub l1' yt) st))
       (\p' s' -> SC (Sub (Lvl p' s') YN) SN)

regularizeSubs :: Subs a -> Subs a
regularizeSubs (SC (Sub r rest) subs)
  | lcolor (isYN rest && isSN subs) r == Red = fixSub r rest subs
regularizeSubs subs = subs

------------------------------------------------------------------------
-- The operations

-- Fast paths.  If the digit being changed keeps its color, the level's color
-- is unchanged, so nothing below can be affected and no repair is needed:
--   cons/snoc  onto a digit of size 1..bGreen-1   (yellow/green -> green/yellow-or-green)
--   uncons     from a digit of size 3..bGreen+1
-- A digit growing from bGreen to bGreen+1 turns green->yellow, which can only
-- matter if the level was green (it then stops heading a substack, and the
-- next head must be checked).  Everything else goes through 'place' in
-- NOINLINE slow-path functions that take the digits' fields unpacked, so no
-- Dig boxes are allocated on the fast path.  The wrappers are INLINE so that,
-- at a call site, the Maybe/tuple/Deque cells of a fast-path operation vanish.

cons :: a -> Deque a -> Deque a
cons x Nil = Deque 1 1 (SCons x SEmpty) 0 SEmpty YN SN
cons x (Deque sz n l m r tl subs)
  | n >= 1 && n < bGreen = Deque (sz + 1) (n + 1) (SCons x l) m r tl subs
  | n == bGreen          = Deque (sz + 1) (n + 1) (SCons x l) m r tl (greenToYellow n m tl subs)
  | otherwise            = consSlow x sz n l m r tl subs
{-# INLINE cons #-}

snoc :: Deque a -> a -> Deque a
snoc Nil x = Deque 1 0 SEmpty 1 (SCons x SEmpty) YN SN
snoc (Deque sz n l m r tl subs) x
  | m >= 1 && m < bGreen = Deque (sz + 1) n l (m + 1) (SCons x r) tl subs
  | m == bGreen          = Deque (sz + 1) n l (m + 1) (SCons x r) tl (greenToYellow m n tl subs)
  | otherwise            = snocSlow x sz n l m r tl subs
{-# INLINE snoc #-}

-- The top level (digit sizes d, e) goes from green to yellow because digit d
-- grew past bGreen: if it was green, the first substack head may now be exposed.
greenToYellow :: Int -> Int -> Ys (Node a) b -> Subs b -> Subs b
greenToYellow d e tl subs
  | lcolorN (isYN tl && isSN subs) d e == Green = regularizeSubs subs
  | otherwise                                   = subs
{-# INLINE greenToYellow #-}

consSlow :: a -> Int -> Int -> SList a -> Int -> SList a -> Ys (Node a) b -> Subs b -> Deque a
consSlow x !sz !n l !m r tl subs =
  place (sz + 1) n m (Dig (n + 1) 0 (SCons x l)) (Dig m 0 r) tl subs
{-# NOINLINE consSlow #-}

snocSlow :: a -> Int -> Int -> SList a -> Int -> SList a -> Ys (Node a) b -> Subs b -> Deque a
snocSlow x !sz !n l !m r tl subs =
  place (sz + 1) n m (Dig n 0 l) (Dig (m + 1) 0 (SCons x r)) tl subs
{-# NOINLINE snocSlow #-}

uncons :: Deque a -> Maybe (a, Deque a)
uncons Nil = Nothing
uncons (Deque sz n l m r tl subs) = case l of
  SCons x l' | n >= 3                           -- (a top digit has at most bGreen + 1)
             -> Just (x, Deque (sz - 1) (n - 1) l' m r tl subs)
             | YN <- tl, SN <- subs             -- the only level: no colors to keep
             -> if sz == 1 then Just (x, Nil) else Just (x, Deque (sz - 1) (n - 1) l' m r YN SN)
  _          -> unconsSlow sz n l m r tl subs
{-# INLINE uncons #-}

unconsSlow :: Int -> Int -> SList a -> Int -> SList a -> Ys (Node a) b -> Subs b -> Maybe (a, Deque a)
unconsSlow !sz !n l !m r tl subs
  | isYN tl, isSN subs = case l of              -- the only level: no colors to keep
      SCons x l'
        | sz == 1   -> Just (x, Nil)
        | otherwise -> Just (x, Deque (sz - 1) (n - 1) l' m r YN SN)
      -- everything is in the suffix: leave half of what remains there (all
      -- of it goes to the prefix if that is three elements or fewer)
      SEmpty -> let !rm = m - 1
                    !k  = if rm <= 3 then 0 else rm `div` 2
                in case revS (dropS k r) of
                     SCons x l' | rm == 0   -> Just (x, Nil)
                                | otherwise -> Just (x, Deque rm (rm - k) l' k (takeS k r) YN SN)
                     SEmpty -> Nothing
  | n > 0 = case dpop p of
      (x, p') -> let !d = place (sz - 1) n m p' (Dig m 0 r) tl subs in Just (x, d)
  | otherwise = case popF (const 0) (Lvl p s) of      -- bottom level with empty prefix
      Just (x, Lvl p' s') -> let !d = place (sz - 1) n m p' s' tl subs in Just (x, d)
      Nothing             -> Nothing
  where p = Dig n 0 l; s = Dig m 0 r
{-# NOINLINE unconsSlow #-}

unsnoc :: Deque a -> Maybe (Deque a, a)
unsnoc Nil = Nothing
unsnoc (Deque sz n l m r tl subs) = case r of
  SCons x r' | m >= 3
             -> Just (Deque (sz - 1) n l (m - 1) r' tl subs, x)
             | YN <- tl, SN <- subs
             -> if sz == 1 then Just (Nil, x) else Just (Deque (sz - 1) n l (m - 1) r' YN SN, x)
  _          -> unsnocSlow sz n l m r tl subs
{-# INLINE unsnoc #-}

unsnocSlow :: Int -> Int -> SList a -> Int -> SList a -> Ys (Node a) b -> Subs b -> Maybe (Deque a, a)
unsnocSlow !sz !n l !m r tl subs
  | isYN tl, isSN subs = case r of
      SCons x r'
        | sz == 1   -> Just (Nil, x)
        | otherwise -> Just (Deque (sz - 1) n l (m - 1) r' YN SN, x)
      SEmpty -> let !rm = n - 1
                    !k  = if rm <= 3 then 0 else rm `div` 2      -- these stay in the prefix
                in case revS (dropS k l) of
                     SCons x r' | rm == 0   -> Just (Nil, x)
                                | otherwise -> Just (Deque rm k (takeS k l) (rm - k) r' YN SN, x)
                     SEmpty -> Nothing
  | m > 0 = case dpop s of
      (x, s') -> let !d = place (sz - 1) n m (Dig n 0 l) s' tl subs in Just (d, x)
  | otherwise = case popB (const 0) (Lvl p s) of      -- bottom level with empty suffix
      Just (x, Lvl p' s') -> let !d = place (sz - 1) n m p' s' tl subs in Just (d, x)
      Nothing             -> Nothing
  where p = Dig n 0 l; s = Dig m 0 r
{-# NOINLINE unsnocSlow #-}

------------------------------------------------------------------------
-- Raw view: a deque as a plain list of levels, top first (no color grouping).
-- Only the checker uses it.

data Raw a where
  RNil  :: Raw a
  RCons :: !(Lvl a) -> !(Raw (Node a)) -> Raw a

isRNil :: Raw a -> Bool
isRNil RNil = True
isRNil _    = False

ysRaw :: Ys x b -> Raw b -> Raw x
ysRaw YN rest        = rest
ysRaw (YC l r) rest  = RCons l (ysRaw r rest)

subsRaw :: Subs x -> Raw x
subsRaw SN = RNil
subsRaw (SC (Sub h r) rest) = RCons h (ysRaw r (subsRaw rest))

toRaw :: Deque a -> Raw a
toRaw Nil = RNil
toRaw (Deque _ n l m r tl subs) = RCons (Lvl (Dig n 0 l) (Dig m 0 r)) (ysRaw tl (subsRaw subs))

------------------------------------------------------------------------
-- More list helpers

lenS :: SList a -> Int
lenS = go 0 where go !acc SEmpty = acc
                  go !acc (SCons _ r) = go (acc + 1) r

revS :: SList a -> SList a
revS = go SEmpty where go acc SEmpty = acc
                       go acc (SCons x r) = go (SCons x acc) r

-- reverse xs onto acc
revApp :: SList a -> SList a -> SList a
revApp SEmpty acc       = acc
revApp (SCons x r) acc  = revApp r (SCons x acc)

listS :: SList a -> [a]
listS SEmpty      = []
listS (SCons x r) = x : listS r

-- the digit's elements as stored: in sequence order (prefix) / last-first (suffix)
dFwd, dBwd :: Dig a -> SList a
dFwd (Dig _ _ l) = l
dBwd (Dig _ _ l) = l

-- a digit from its count and elements
mkDig :: (x -> Int) -> Int -> SList x -> Dig x
mkDig sz n l = Dig n (sumSz sz l) l

sumSz :: (x -> Int) -> SList x -> Int
sumSz sz = go 0 where go !acc SEmpty = acc
                      go !acc (SCons x r) = go (acc + sz x) r

-- A digit without its innermost element, and that element.
dInit :: (x -> Int) -> Dig x -> (# Dig x, x #)
dInit sz (Dig n z l) = let !x = nthS (n - 1) l in (# Dig (n - 1) (z - sz x) (takeS (n - 1) l), x #)

-- Cut a forward list of m (0 or >= 2) elements into nodes in one pass: nodes
-- of eight while more than nine elements remain, then threes and twos.
packF :: (x -> Int) -> Int -> SList x -> SList (Node x)
packF sz = go
  where
    go !m l
      | m == 0 = SEmpty
      | m >= 10 || m == 8 = case l of
          SCons a (SCons b (SCons c (SCons d (SCons e (SCons f (SCons g (SCons h r))))))) ->
            SCons (N8 (sz a + sz b + sz c + sz d + sz e + sz f + sz g + sz h) a b c d e f g h) (go (m - 8) r)
          _ -> error "packF"
      | m == 3 || m == 5 || m == 6 || m == 7 || m == 9 = case l of
          SCons a (SCons b (SCons c r)) -> SCons (N3 (sz a + sz b + sz c) a b c) (go (m - 3) r)
          _ -> error "packF"
      | otherwise = case l of
          SCons a (SCons b r) -> SCons (N2 (sz a + sz b) a b) (go (m - 2) r)
          _ -> error "packF"
{-# INLINE packF #-}

------------------------------------------------------------------------
-- The levels from some depth down, as a value: a run of yellow levels, then
-- substacks.  This is what a Deque holds below its top level, and what any
-- level has below it.  We call it regular if its first level that isn't
-- yellow is green (or there is none): then it can sit under any level, a red
-- one included.

data Rest x where
  Rest :: !(Ys x b) -> !(Subs b) -> Rest x

noRest :: Rest (Node x)
noRest = Rest YN SN

-- the first level and what is below it
viewRest :: Rest (Node a) -> Maybe (Lvl (Node a), Rest (Node (Node a)))
viewRest (Rest (YC l r) subs)            = Just (l, Rest r subs)
viewRest (Rest YN (SC (Sub l r) st))     = Just (l, Rest r st)
viewRest (Rest YN SN)                    = Nothing
{-# INLINE viewRest #-}

isNoRest :: Rest x -> Bool
isNoRest (Rest ys subs) = isYN ys && isSN subs

-- Put a level with any digits (0 to bGreen + 2 elements each) on top of
-- levels that were regular under whatever they came from; the result is
-- regular.  Under a green level anything goes; otherwise the levels below
-- are made regular first, and a red level is then repaired, which moves at
-- most one node per end between it and the level below.
mkRest :: Lvl (Node a) -> Rest (Node (Node a)) -> Rest (Node a)
mkRest l (Rest ys subs)
  | bottom && isEmptyLvl l = noRest
  | otherwise = case lcolor bottom l of
      Green  -> Rest YN (SC (Sub l ys) subs)
      Yellow -> Rest (YC l ys) (regularizeSubs subs)
      Red    -> Rest YN (fixSub l ys (regularizeSubs subs))
  where bottom = isYN ys && isSN subs

-- The same for the top level.
mkTop :: Int -> Dig a -> Dig a -> Rest (Node a) -> Deque a
mkTop sz p s (Rest tl subs)
  | bottom && dcount p == 0 && dcount s == 0 = Nil
  | otherwise = case lcolorD bottom p s of
      Green  -> mkDeque sz p s tl subs
      Yellow -> mkDeque sz p s tl (regularizeSubs subs)
      Red    -> fixTopRed sz p s tl (regularizeSubs subs)
  where bottom = isYN tl && isSN subs

------------------------------------------------------------------------
-- Append, O(log (min n m)).
--
-- A deque's sequence at level k is  prefix_k ++ (nodes of level k+1, unpacked)
-- ++ suffix_k.  So for A ++ B, level k of the result keeps A's prefix and B's
-- suffix, and the seam  suffix_k(A) ++ (nodes from the seam one level up) ++
-- prefix_k(B)  is packed into nodes that join the sequence of level k+1.  The
-- seam is not a multiple of eight, so those nodes have eight, three or two
-- children: that is what the node sizes are for.
--
-- When one side runs out of levels, the nodes still carried are pushed onto
-- the near end of the other side's next level; a digit that overflows keeps
-- five elements and hands the rest down as nodes, which soon stops.  The
-- levels below that are shared with the argument.
--
-- Each level of the result is put on top of the levels below it with
-- 'mkRest', which repairs it if it is red, so the digits taken from A and B
-- need no preparation.

-- Level k of A and of B (with the levels below each) and the carry (c nodes,
-- in sequence order) from the seam above: level k of the result, and the
-- levels below it.  'fix' repairs a red level that isn't the bottom.
catLvl :: (x -> Int)
       -> (Lvl x -> Rest (Node x) -> (# Lvl x, Rest (Node x) #))
       -> Int -> SList x
       -> Lvl x -> Rest (Node x) -> Lvl x -> Rest (Node x)
       -> (# Lvl x, Rest (Node x) #)
catLvl sz fix = go
  where
    go !c carry la@(Lvl pA sA) ra lb@(Lvl pB sB) rb
      -- both end here and fit in one level
      | endA, endB, total <= 2 * bGreen =
          let xs = appendS (dFwd pA) (revApp (dBwd sA) (appendS carry (appendS (dFwd pB) (revS (dBwd sB)))))
          in (# splitLvl sz (if total <= 3 then total else total `div` 2) total xs, noRest #)
      | m == 0 = (# Lvl pA sB, catRest 0 SEmpty ra rb #)
      | m >= 2 = let !nodes = packF sz m seam in (# Lvl pA sB, catRest (lenS nodes) nodes ra rb #)
      -- One element can't make a node.  It is there because a digit next to
      -- the seam is empty.  If that is in a red level, repair the level and
      -- try again; if it is in a bottom level, the seam borrows a neighbour
      -- from the bottom level's other digit.
      | dcount sA == 0, not endA = case fix la ra of (# la', ra' #) -> go c carry la' ra' lb rb
      | dcount pB == 0, not endB = case fix lb rb of (# lb', rb' #) -> go c carry la ra lb' rb'
      | dcount sA == 0 = case dInit sz pA of
          (# pA', x #) -> let !nodes = packF sz 2 (SCons x seam) in (# Lvl pA' sB, catRest 1 nodes ra rb #)
      | otherwise = case dInit sz sB of
          (# sB', x #) -> let !nodes = packF sz 2 (appendS seam (SCons x SEmpty)) in (# Lvl pA sB', catRest 1 nodes ra rb #)
      where
        endA  = isNoRest ra
        endB  = isNoRest rb
        m     = dcount sA + c + dcount pB
        total = dcount pA + m + dcount sB
        seam  = revApp (dBwd sA) (appendS carry (dFwd pB))
{-# INLINE catLvl #-}

-- The levels below the top: A's, the carry, B's.
catRest :: Int -> SList (Node x) -> Rest (Node x) -> Rest (Node x) -> Rest (Node x)
catRest !c carry ra rb = case viewRest ra of
  Nothing -> growFront c carry rb
  Just (la, ra1) -> case viewRest rb of
    Nothing -> growBack c carry ra
    Just (lb, rb1) -> case catLvl nodeSize fixLvl c carry la ra1 lb rb1 of
      (# l, lower #) -> mkRest l lower

fixLvl :: Lvl (Node x) -> Rest (Node (Node x)) -> (# Lvl (Node x), Rest (Node (Node x)) #)
fixLvl l r = case viewRest (mkRest l r) of
  Just (l', r') -> (# l', r' #)
  Nothing       -> error "fixLvl: the level vanished"

-- Push c nodes (in sequence order) onto the front of these levels.
growFront :: Int -> SList (Node x) -> Rest (Node x) -> Rest (Node x)
growFront !c carry rb
  | c == 0 = rb
  | otherwise = case viewRest rb of
      Nothing -> mkRest (Lvl (mkDig nodeSize c carry) dnil) noRest
      Just (Lvl (Dig n z l) s, rb1)
        | c + n <= bGreen -> mkRest (Lvl (Dig (c + n) (z + sumSz nodeSize carry) (appendS carry l)) s) rb1
        | otherwise ->
            let allL   = appendS carry l
                !nodes = packF nodeSize (c + n - 5) (dropS 5 allL)
            in mkRest (Lvl (mkDig nodeSize 5 (takeS 5 allL)) s) (growFront (lenS nodes) nodes rb1)

-- ... or onto the back.
growBack :: Int -> SList (Node x) -> Rest (Node x) -> Rest (Node x)
growBack !c carry ra
  | c == 0 = ra
  | otherwise = case viewRest ra of
      Nothing -> mkRest (Lvl (mkDig nodeSize c carry) dnil) noRest
      Just (Lvl p (Dig n z l), ra1)
        | c + n <= bGreen -> mkRest (Lvl p (Dig (c + n) (z + sumSz nodeSize carry) (revApp carry l))) ra1
        | otherwise ->
            let allB   = revApp carry l                   -- last element first
                !nodes = packF nodeSize (c + n - 5) (revS (dropS 5 allB))
            in mkRest (Lvl p (mkDig nodeSize 5 (takeS 5 allB))) (growBack (lenS nodes) nodes ra1)

-- Appending a small deque element by element beats the general algorithm,
-- and leaves full nodes behind.
bulkLimit :: Int
bulkLimit = 8

-- | Concatenate.  O(log (min n m)).
append :: Deque a -> Deque a -> Deque a
append Nil b = b
append a Nil = a
append a@(Deque szA npA plA nsA slA tlA subsA) b@(Deque szB npB plB nsB slB tlB subsB)
  -- A small single-level deque joins the digit next to it in one step.  If
  -- the digit stays green nothing else changes; otherwise one repair (which
  -- sheds a node of eight) makes it green, so it may get up to bGreen + wNode.
  | szB <= bulkLimit, YN <- tlB, SN <- subsB, nsA + szB <= bGreen + wNode =
      let s' = appendS slB (revApp plB slA)
      in if nsA >= 1 && nsA + szB <= bGreen
           then Deque (szA + szB) npA plA (nsA + szB) s' tlA subsA
           else mkTop (szA + szB) (Dig npA 0 plA) (Dig (nsA + szB) 0 s') (Rest tlA subsA)
  | szA <= bulkLimit, YN <- tlA, SN <- subsA, npB + szA <= bGreen + wNode =
      let p' = appendS plA (revApp slA plB)
      in if npB >= 1 && npB + szA <= bGreen
           then Deque (szA + szB) (npB + szA) p' nsB slB tlB subsB
           else mkTop (szA + szB) (Dig (npB + szA) 0 p') (Dig nsB 0 slB) (Rest tlB subsB)
  | szB <= bulkLimit = foldlD' snoc a b
  | szA <= bulkLimit = front a b
  | otherwise =
      case catLvl (const 1) (\_ _ -> error "append: a red top level") 0 SEmpty
             (Lvl (Dig npA 0 plA) (Dig nsA 0 slA)) (Rest tlA subsA)
             (Lvl (Dig npB 0 plB) (Dig nsB 0 slB)) (Rest tlB subsB) of
        (# Lvl p s, lower #) -> mkTop (szA + szB) p s lower
  where
    front x acc = case unsnoc x of            -- consume a from its back, cons onto b
      Nothing       -> acc
      Just (x', e)  -> front x' (cons e acc)

------------------------------------------------------------------------
-- take and drop.
--
-- Cutting at a position is the same descent as 'lookup'.  To remove the first
-- k leaves, find the level whose digit holds the cut.  The cut element, if
-- the cut falls inside it (a node), is split: its remaining children become
-- the new outer digit of the level above, and the child containing the cut
-- is split in turn one level up, so every level above the cut ends up with a
-- fresh outer digit of at most seven elements and an untouched inner digit.
-- If the cut lies in an inner digit, everything below that level is gone and
-- the level becomes the bottom.  Levels below the cut are shared with the
-- original.  On the way back up each level is put on top of the (regular)
-- levels below it with 'mkRest', which repairs it if its new digit came out
-- empty.  O(log n).  'take' is the mirror image (remove from the back), so
-- both share the code, parametrized by which digit is "near" the cut end.

-- (near digit, far digit)
nearFar :: Bool -> Lvl x -> (Dig x, Dig x)
nearFar True  (Lvl p s) = (p, s)
nearFar False (Lvl p s) = (s, p)
{-# INLINE nearFar #-}

fromNearFar :: Bool -> Dig x -> Dig x -> Lvl x
fromNearFar True  n f = Lvl n f
fromNearFar False n f = Lvl f n
{-# INLINE fromNearFar #-}

-- an element the cut falls inside, with the number of leaves to cut from its near end
data Part x = NoPart | Part !x !Int

-- Remove k leaves from the near end of a list (near end first) of n elements
-- and z leaves, k <= z.  Gives what remains (count, leaves, list); an element
-- the cut falls inside is removed too, and returned.
cutDig :: (x -> Int) -> Int -> Int -> Int -> SList x -> (# Int, Int, SList x, Part x #)
cutDig sz = go
  where
    go !k !n !z l
      | k == 0 = (# n, z, l, NoPart #)
      | otherwise = case l of
          SCons e r -> let !ze = sz e
                       in if k < ze then (# n - 1, z - ze, r, Part e k #)
                          else go (k - ze) (n - 1) (z - ze) r
          SEmpty -> error "cutDig: out of range"
{-# INLINE cutDig #-}

-- Remove k leaves (of tot) from the near end of these levels.  If the cut falls inside an element of the first level, that
-- element is removed and returned: its children beyond the cut belong to the
-- level above.
cutRest :: Bool -> Int -> Int -> Rest (Node a) -> (# Rest (Node a), Part (Node a) #)
cutRest fwd !k !tot rest
  | k == 0 = (# rest, NoPart #)
  | otherwise = case viewRest rest of
      Nothing -> error "cutRest: out of levels"
      Just (l, rest1) -> case nearFar fwd l of
        (Dig cn zn nl, f@(Dig cf zf fl))
          | k < zn -> case cutDig nodeSize k cn zn nl of
              (# c', z', l', part #) ->
                (# mkRest (fromNearFar fwd (Dig c' z' l') f) rest1, part #)
          | k < tot - zf -> case cutRest fwd (k - zn) (tot - zn - zf) rest1 of
              (# rest1', NoPart #) -> (# mkRest (fromNearFar fwd dnil f) rest1', NoPart #)
              (# rest1', Part e o #) ->
                case cutDig nodeSize o (nodeArity e) (nodeSize e) (if fwd then nodeToFwd e else nodeToBwd e) of
                  (# c', z', l', part #) -> (# mkRest (fromNearFar fwd (Dig c' z' l') f) rest1', part #)
          -- in the far digit: this level becomes the bottom
          | otherwise -> case cutDig nodeSize (k - (tot - zf)) cf zf (revS fl) of
              (# c', z', l', part #) -> (# mkRest (fromNearFar fwd (Dig c' z' l') dnil) noRest, part #)

drop :: Int -> Deque a -> Deque a
drop _ Nil = Nil
drop i d@(Deque sz np pl ns sl tl subs)
  | i <= 0      = d
  | i >= sz     = Nil
  | i < np      = mkTop (sz - i) (Dig (np - i) 0 (dropS i pl)) (Dig ns 0 sl) (Rest tl subs)
  | i < sz - ns = case cutRest True (i - np) (sz - np - ns) (Rest tl subs) of
      (# rest, NoPart #)   -> mkTop (sz - i) dnil (Dig ns 0 sl) rest
      (# rest, Part e o #) -> mkTop (sz - i) (Dig (nodeArity e - o) 0 (dropS o (nodeToFwd e))) (Dig ns 0 sl) rest
  | otherwise   = let c = sz - i                  -- what is left is the end of the suffix
                  in Deque c 0 SEmpty c (takeS c sl) YN SN

take :: Int -> Deque a -> Deque a
take _ Nil = Nil
take i d@(Deque sz np pl ns sl tl subs)
  | i <= 0      = Nil
  | i >= sz     = d
  | k < ns      = mkTop i (Dig np 0 pl) (Dig (ns - k) 0 (dropS k sl)) (Rest tl subs)
  | k < sz - np = case cutRest False (k - ns) (sz - np - ns) (Rest tl subs) of
      (# rest, NoPart #)   -> mkTop i (Dig np 0 pl) dnil rest
      (# rest, Part e o #) -> mkTop i (Dig np 0 pl) (Dig (nodeArity e - o) 0 (dropS o (nodeToBwd e))) rest
  | otherwise   = Deque i i (takeS i pl) 0 SEmpty YN SN      -- the start of the prefix
  where k = sz - i                                -- to remove from the back

------------------------------------------------------------------------
-- Inspection

-- | The elements in order.  Lazy: the list is produced as it is consumed.
toList :: Deque a -> [a]
toList = foldrI (:) []

fromList :: [a] -> Deque a
fromList = L.foldl' snoc empty

-- | @fromFunction n f@ is @f 0, f 1, ..., f (n - 1)@.
fromFunction :: Int -> (Int -> a) -> Deque a
fromFunction n f
  | n < 0     = error "Deque.fromFunction called with negative len"
  | otherwise = go 0 empty
  where go !i !acc | i == n    = acc
                   | otherwise = go (i + 1) (snoc acc (f i))

singleton :: a -> Deque a
singleton x = Deque 1 1 (SCons x SEmpty) 0 SEmpty YN SN

-- O(1): the total is stored in the Deque.
size :: Deque a -> Int
size Nil            = 0
size (Deque sz _ _ _ _ _ _) = sz

-- Direct lookup by position.  Walk the levels top to bottom with polymorphic recursion.
-- At each level we look for the leaf with i leaves before it and j after it
-- (within the sequence of this level and everything below).  A hit in a digit
-- is a scan over the digit's elements, adding up their sizes; otherwise the
-- leaf lies in the part below, which hands back the element of the level
-- below containing it, and we pick the right child.  Results flow upward in
-- unboxed tuples, so no closures or intermediate lists are built: the only
-- allocation is the final Just.
lookup :: Int -> Deque a -> Maybe a
lookup !_ Nil = Nothing
lookup !i (Deque n np pl ns sl tl subs)
  | i < 0 || i >= n = Nothing
  | i < np          = let !r = nthS i pl in Just r
  | j < ns          = let !r = nthS j sl in Just r
  | otherwise       = case findYs 3 (i - np) (j - ns) tl subs of
                        (# nd, off# #) -> let !r = nodeAt (I# off#) nd in Just r
  where !j = n - 1 - i

nthS :: Int -> SList a -> a
nthS k (SCons x r) | k == 0    = x
                   | otherwise = nthS (k - 1) r
nthS _ SEmpty = error "nthS: out of range"

-- sh: log2 of the number of leaves under a full element of this level
findYs :: Int -> Int -> Int -> Ys x b -> Subs b -> (# x, Int# #)
findYs !sh !i !j YN subs          = findSubs sh i j subs
findYs !sh !i !j (YC l r) subs    = findLvl sh i j l r subs

findSubs :: Int -> Int -> Int -> Subs x -> (# x, Int# #)
findSubs _ _ _ SN = error "index: ran out of levels"
findSubs !sh !i !j (SC (Sub l r) rest) = findLvl sh i j l r rest

findLvl :: Int -> Int -> Int -> Lvl (Node a) -> Ys (Node (Node a)) b -> Subs b -> (# Node a, Int# #)
findLvl !sh !i !j (Lvl (Dig _ zp pl) (Dig _ zs sl)) r rest
  | i < zp    = scanFront i pl
  | j < zs    = scanBack j sl
  | otherwise = case findYs (sh + 3) (i - zp) (j - zs) r rest of
                  (# nd, o# #) -> childAt sh (I# o#) nd

-- the node holding the leaf with k leaves before it in a digit that has it
scanFront :: Int -> SList (Node a) -> (# Node a, Int# #)
scanFront !k (SCons e r) = let !z = nodeSize e
                           in if k < z then (case k of I# k# -> (# e, k# #)) else scanFront (k - z) r
scanFront _ SEmpty = error "scanFront"

-- ... or with k leaves after it, in a suffix digit (its list runs from the back)
scanBack :: Int -> SList (Node a) -> (# Node a, Int# #)
scanBack !k (SCons e r) = let !z = nodeSize e
                          in if k < z then (case z - 1 - k of I# o# -> (# e, o# #)) else scanBack (k - z) r
scanBack _ SEmpty = error "scanBack"

-- the child of a node (of nodes) containing leaf offset k, and the offset in it
childAt :: Int -> Int -> Node (Node y) -> (# Node y, Int# #)
childAt !sh !k0 nd = case nd of
  N8 sz a b c d e f g h
    | sz == 8 `unsafeShiftL` sh -> case nodeAt (k0 `unsafeShiftR` sh) nd of     -- all children full
        c' -> fin c' (k0 .&. ((1 `unsafeShiftL` sh) - 1))
    | otherwise ->
    let !za = nodeSize a in if k0 < za then fin a k0 else
    let !k1 = k0 - za; !zb = nodeSize b in if k1 < zb then fin b k1 else
    let !k2 = k1 - zb; !zc = nodeSize c in if k2 < zc then fin c k2 else
    let !k3 = k2 - zc; !zd = nodeSize d in if k3 < zd then fin d k3 else
    let !k4 = k3 - zd; !ze = nodeSize e in if k4 < ze then fin e k4 else
    let !k5 = k4 - ze; !zf = nodeSize f in if k5 < zf then fin f k5 else
    let !k6 = k5 - zf; !zg = nodeSize g in if k6 < zg then fin g k6 else
    fin h (k6 - zg)
  N3 _ a b c ->
    let !za = nodeSize a in if k0 < za then fin a k0 else
    let !k1 = k0 - za; !zb = nodeSize b in if k1 < zb then fin b k1 else
    fin c (k1 - zb)
  N2 _ a b ->
    let !za = nodeSize a in if k0 < za then fin a k0 else fin b (k0 - za)
  where
    fin c k = case k of I# k# -> (# c, k# #)
    {-# INLINE fin #-}

------------------------------------------------------------------------
-- Checking (for tests)

-- | Check the invariants the operations rely on.  @Left@ describes the first
-- violation found.  O(n).
--
-- * the stored counts are right: the total, each digit's length and leaf
--   count, each node's size
-- * no digit has more than @bGreen + 2@ elements and the bottom level isn't empty
-- * the levels are regular: ignoring yellow levels, the first is green and no
--   two red ones are adjacent
-- * the levels are grouped by color: runs hold yellow levels only, and every
--   substack is headed by a level that isn't yellow
valid :: Deque a -> Either String ()
valid Nil = Right ()
valid d@(Deque sz _ _ _ _ tl subs) = do
  (total, colors) <- checkRaw True (const (Right 1)) (toRaw d)
  unless (total == sz) $ Left ("the size is " ++ show sz ++ " but there are " ++ show total ++ " elements")
  case filter (/= Yellow) colors of
    Red : _ -> Left ("the first level that isn't yellow is red: " ++ show colors)
    cs | or (zipWith (\a b -> a == Red && b == Red) cs (L.drop 1 cs)) ->
           Left ("two red levels with no green one between them: " ++ show colors)
    _ -> Right ()
  zipWithM_ grouped (L.drop 1 colors) (replicate (lenYs tl) False ++ subHeads subs)
  where
    grouped c isHead
      | isHead && c == Yellow     = Left "a substack is headed by a yellow level"
      | not isHead && c /= Yellow = Left ("a " ++ show c ++ " level in a run of yellow ones")
      | otherwise                 = Right ()

lenYs :: Ys a b -> Int
lenYs YN       = 0
lenYs (YC _ r) = 1 + lenYs r

-- one Bool per level below the top run: is it the head of a substack?
subHeads :: Subs a -> [Bool]
subHeads SN                     = []
subHeads (SC (Sub _ r) rest)    = True : (replicate (lenYs r) False ++ subHeads rest)

-- the number of leaves under these levels and the levels' colors, top first
checkRaw :: Bool -> (x -> Either String Int) -> Raw x -> Either String (Int, [Color])
checkRaw _ _ RNil = Right (0, [])
checkRaw top leaves (RCons (Lvl p s) rest) = do
  zp <- checkDig top leaves p
  zs <- checkDig top leaves s
  (zr, cs) <- checkRaw False (checkNode leaves) rest
  let bottom = isRNil rest
  when (bottom && dcount p + dcount s == 0) $ Left "the bottom level is empty"
  pure (zp + zs + zr, lcolorN bottom (dcount p) (dcount s) : cs)

checkDig :: Bool -> (x -> Either String Int) -> Dig x -> Either String Int
checkDig top leaves (Dig n z l) = do
  zs <- traverse leaves (listS l)
  unless (n == L.length zs) $ Left ("a digit of " ++ show (L.length zs) ++ " elements has count " ++ show n)
  when (n > bGreen + 2) $ Left ("a digit has " ++ show n ++ " elements")
  unless (top || z == sum zs) $ Left ("a digit with " ++ show (sum zs) ++ " leaves has leaf count " ++ show z)
  pure (sum zs)

checkNode :: (x -> Either String Int) -> Node x -> Either String Int
checkNode leaves nd = do
  zs <- traverse leaves (listS (nodeToFwd nd))
  unless (sum zs == nodeSize nd) $ Left ("a node with " ++ show (sum zs) ++ " leaves has size " ++ show (nodeSize nd))
  pure (nodeSize nd)

------------------------------------------------------------------------
-- Folds.  These walk the structure directly: prefix, the levels below, then
-- the suffix (whose list runs back to front).  Below the top level an element
-- is a node, so the function handed down folds over a node's children.

-- | Right fold, lazy in the accumulator.
foldrD :: (a -> r -> r) -> r -> Deque a -> r
foldrD _ z Nil = z
foldrD f z (Deque _ _ l _ r tl subs) =
  foldrFwd f (foldrYs (foldrNode f) tl subs (foldrBwd f z r)) l

-- The same, inlined where it is used, so that a known function is applied
-- directly to the children of the leaf nodes, where nearly all the elements
-- are.  With (:) that builds a leaf's eight cells with no calls in between.
foldrI :: (a -> r -> r) -> r -> Deque a -> r
foldrI _ z Nil = z
foldrI f z (Deque _ _ l _ r tl subs) =
  foldrFwd f (foldrYs (\nd acc -> foldrNodeI f nd acc) tl subs (foldrBwd f z r)) l
{-# INLINE foldrI #-}

foldrNodeI :: (x -> r -> r) -> Node x -> r -> r
foldrNodeI f (N8 _ a b c d e g h i) z = f a (f b (f c (f d (f e (f g (f h (f i z)))))))
foldrNodeI f (N3 _ a b c) z           = f a (f b (f c z))
foldrNodeI f (N2 _ a b) z             = f a (f b z)
{-# INLINE foldrNodeI #-}

-- a list in sequence order / a list that runs back to front (a short one)
foldrFwd, foldrBwd :: (x -> r -> r) -> r -> SList x -> r
foldrFwd f z = go where go SEmpty = z
                        go (SCons x r) = f x (go r)
foldrBwd f = go where go acc SEmpty = acc
                      go acc (SCons x r) = go (f x acc) r

foldrNode :: (x -> r -> r) -> Node x -> r -> r
foldrNode f (N8 _ a b c d e g h i) z = f a (f b (f c (f d (f e (f g (f h (f i z)))))))
foldrNode f (N3 _ a b c) z           = f a (f b (f c z))
foldrNode f (N2 _ a b) z             = f a (f b z)

foldrYs :: (x -> r -> r) -> Ys x b -> Subs b -> r -> r
foldrYs f YN subs z = foldrSubs f subs z
foldrYs f (YC (Lvl (Dig _ _ p) (Dig _ _ s)) rest) subs z =
  foldrFwd f (foldrYs (foldrNode f) rest subs (foldrBwd f z s)) p

foldrSubs :: (x -> r -> r) -> Subs x -> r -> r
foldrSubs _ SN z = z
foldrSubs f (SC (Sub (Lvl (Dig _ _ p) (Dig _ _ s)) rest) more) z =
  foldrFwd f (foldrYs (foldrNode f) rest more (foldrBwd f z s)) p

-- | Strict left fold.
foldlD' :: (r -> a -> r) -> r -> Deque a -> r
foldlD' _ !z Nil = z
foldlD' f !z (Deque _ _ l _ r tl subs) =
  foldlBwd f (foldlYs (foldlNode f) (foldlFwd f z l) tl subs) r

foldlFwd, foldlBwd :: (r -> x -> r) -> r -> SList x -> r
foldlFwd f = go where go !acc SEmpty = acc
                      go !acc (SCons x r) = go (f acc x) r
foldlBwd f !z = go where go SEmpty = z                      -- at most a digit deep
                         go (SCons x r) = let !acc = go r in f acc x

foldlNode :: (r -> x -> r) -> r -> Node x -> r
foldlNode f !z (N8 _ a b c d e g h i) =
  let !z1 = f z a; !z2 = f z1 b; !z3 = f z2 c; !z4 = f z3 d
      !z5 = f z4 e; !z6 = f z5 g; !z7 = f z6 h
  in f z7 i
foldlNode f !z (N3 _ a b c) = let !z1 = f z a; !z2 = f z1 b in f z2 c
foldlNode f !z (N2 _ a b)   = let !z1 = f z a in f z1 b

foldlYs :: (r -> x -> r) -> r -> Ys x b -> Subs b -> r
foldlYs f !z YN subs = foldlSubs f z subs
foldlYs f !z (YC (Lvl (Dig _ _ p) (Dig _ _ s)) rest) subs =
  foldlBwd f (foldlYs (foldlNode f) (foldlFwd f z p) rest subs) s

foldlSubs :: (r -> x -> r) -> r -> Subs x -> r
foldlSubs _ !z SN = z
foldlSubs f !z (SC (Sub (Lvl (Dig _ _ p) (Dig _ _ s)) rest) more) =
  foldlBwd f (foldlYs (foldlNode f) (foldlFwd f z p) rest more) s

------------------------------------------------------------------------
-- The names Data.Sequence uses, so that this module can stand in for it.

type Seq = Deque

length :: Deque a -> Int
length = size
{-# INLINE length #-}

null :: Deque a -> Bool
null Nil = True
null _   = False
{-# INLINE null #-}

infixr 5 <|
infixl 5 |>
infixr 5 ><

(<|) :: a -> Deque a -> Deque a
(<|) = cons
{-# INLINE (<|) #-}

(|>) :: Deque a -> a -> Deque a
(|>) = snoc
{-# INLINE (|>) #-}

(><) :: Deque a -> Deque a -> Deque a
(><) = append
{-# INLINE (><) #-}

infixr 5 :<|
infixl 5 :|>

pattern Empty :: Deque a
pattern Empty <- (null -> True) where
  Empty = Nil

pattern (:<|) :: a -> Deque a -> Deque a
pattern x :<| xs <- (uncons -> Just (x, xs)) where
  x :<| xs = cons x xs

pattern (:|>) :: Deque a -> a -> Deque a
pattern xs :|> x <- (unsnoc -> Just (xs, x)) where
  xs :|> x = snoc xs x

{-# COMPLETE (:<|), Empty #-}
{-# COMPLETE (:|>), Empty #-}

-- | @splitAt i d = (take i d, drop i d)@
splitAt :: Int -> Deque a -> (Deque a, Deque a)
splitAt i d = (take i d, drop i d)

-- | A stable sort.  O(n log n); goes through a list.
sort :: (Ord a) => Deque a -> Deque a
sort = sortBy compare

sortBy :: (a -> a -> Ordering) -> Deque a -> Deque a
sortBy cmp = fromList . L.sortBy cmp . toList

-- | The same as 'sort' here; Data.Sequence has both.
unstableSort :: (Ord a) => Deque a -> Deque a
unstableSort = sort

unstableSortBy :: (a -> a -> Ordering) -> Deque a -> Deque a
unstableSortBy = sortBy

intersperse :: a -> Deque a -> Deque a
intersperse sep = fromList . L.intersperse sep . toList

reverse :: Deque a -> Deque a
reverse = foldlD' (flip cons) empty

------------------------------------------------------------------------
-- Instances

instance Semigroup (Deque a) where
  (<>) = append

instance Monoid (Deque a) where
  mempty = empty

instance Foldable Deque where
  foldr = foldrD
  foldl' = foldlD'
  toList = toList
  length = size
  null = null

-- | Rebuilds the sequence.  O(n).
instance Functor Deque where
  fmap f = foldlD' (\acc x -> snoc acc (f x)) empty

-- | Rebuilds the sequence.  O(n).
instance Traversable Deque where
  traverse f d = fromList <$> traverse f (toList d)

instance (Eq a) => Eq (Deque a) where
  a == b = size a == size b && toList a == toList b

-- | Lexicographic, as for lists.
instance (Ord a) => Ord (Deque a) where
  compare a b = compare (toList a) (toList b)

instance Eq1 Deque where
  liftEq eq a b = size a == size b && liftEq eq (toList a) (toList b)

instance Ord1 Deque where
  liftCompare cmp a b = liftCompare cmp (toList a) (toList b)

instance (Show a) => Show (Deque a) where
  showsPrec p d = showParen (p > 10) $ showString "fromList " . shows (toList d)

instance Show1 Deque where
  liftShowsPrec _ sl p d = showParen (p > 10) $ showString "fromList " . sl (toList d)

-- | The structure is always evaluated; this evaluates the elements fully.
instance (NFData a) => NFData (Deque a) where
  rnf = foldlD' (\() x -> rnf x) ()

instance Exts.IsList (Deque a) where
  type Item (Deque a) = a
  fromList = fromList
  toList = toList
